### PR TITLE
[#146] ensure map is fully displayed before initialization.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by allenhwkim** [comment]
Currently map is initialized after api is loaded.
How about initializing the map after api is loaded AND view is initialized.

**Comment by aitboudad** [comment]
it doesn't solve the issue when the map is used inside `ng-content`, I used this proposal since a while and it fit to my usecase

**Comment by Leanvitale** [comment]
Hello! i have the same problem, how i solve?

**Comment by AdrianMrn** [comment]
Hi!
I can't seem to figure out how to implement this.. I want to show a loading icon on my screen until the map has initialized, and remove the loading icon when it has initialized.

Is there a way to do this? Thanks

**Comment by aitboudad** [comment]
@AdrianMrn https://github.com/ng2-ui/map/blob/master/src/components/ngui-map.component.ts#L57

**Pull request merged**
