### PR TITLE
add angular 6 support

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by aitboudad** [comment]
can you try with:
```bash
npm i @ngui/map --next
```

**Comment by shyamal890** [comment]
It installs the current 0.20.2 version only. Which has https://github.com/ng2-ui/map/issues/265 error

**Comment by aitboudad** [comment]
angular 6 support is landed in `0.30.0` verison and not `0.20.2`, please ensure you used the right version.
Thanks!

**Comment by aitboudad** [comment]
@shyamal890 published a fix in `0.30.1`, could please try it and let me know if it's work ?

**Pull request merged**
