### PR TITLE
Remove console.log messages

### PR DESCRIPTION
**Pull request by cosmin-dumitrache**
I had to remove all the console.log() messages for my project because it was polluting the console with log messages unrelated to my app.

Please feel free to merge if you think it's useful for other users.

### CODE REVIEW

**Comment by aitboudad** [comment]
already done in https://github.com/ng2-ui/map/pull/151 (v0.18.4), which version you use?

**Comment by cosmin-dumitrache** [comment]
Strange, I was using v0.18.4 from NPM ...

**Comment by allenhwkim** [comment]
This `console.log` is very necessary for debugging. I wouldn't recommend to remove those.
The production version always remove console.log, and you should not see those.
Please use `map` not as source but as a module.
https://github.com/ng2-ui/map/blob/master/webpack.config.js#L40

**Comment by cosmin-dumitrache** [comment]
@allenhwkim That sounds like a good approach. As far as I can see, the production version currently doesn't remove the console.log messages (at least the one you get out of NPM and the one you linked to).

**Comment by aitboudad** [comment]
close in favor of #188

**Pull request closed without merging**
