### PR TITLE
[places-auto-complete] use NgMapApiLoader

### LINKED ISSUE #133: Input "places-auto-complete" + <ngui-map> makes map not displayed.
Input with directive "places-auto-complete" in conjonction with a map
results with the map invisible.

We can see this behavior even in this demo : 
https://rawgit.com/ng2-ui/map/master/app/index.html#/places-auto-complete

### PR DESCRIPTION
**Pull request by aitboudad**
fix #133

### CODE REVIEW

**Comment by allenhwkim** [comment]
thanks @aitboudad

**Comment by hoisel** [comment]
When will this fix be released?

**Comment by aitboudad** [comment]
@hoisel already released, use `0.18.0` version

**Comment by hoisel** [comment]
Cool, thanks!!

**Pull request merged**
